### PR TITLE
Tweaks

### PR DESCRIPTION
**Pull request by stdavis**
Thanks for the great project! It's allowing me to do some testing on my projects that wasn't possible before.

These are just a few tweaks that I had to make to make it work in my environment.

If you decide to merge this PR, I'd be happy to sign the Adobe CLA. Please send me a link to it.

### CODE REVIEW

**Comment by Stuk** [comment]
Thanks for the PR @stdavis! The CLA is available [here](http://adobe.ly/1NodYqm). Once I get a notification that you've signed it then I'll merge this.

I'm glad that you've found this project useful :)

**Comment by stdavis** [comment]
Done.

Would it be possible for you to push a new version to npm to make it easier for me to add this to my build server?

Thanks!

**Comment by Stuk** [comment]
Merged and v1.1.0 published. Thank you!

**Comment by stdavis** [comment]
You are very welcome. Thanks for the quick response.

**Pull request merged**
